### ISSUE TITLE
Can't install with pip3

### ISSUE THREAD

**Issue by SilkAndSlug** [budziq/link-checker#2]
`pip3 install link-checker` fails with the below. This is on Debian Stretch; `pip3 -V` returns `pip 19.0.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)`

    Collecting link-checker
      Downloading https://files.pythonhosted.org/packages/db/2a/0dd919b08c1eec2874e31df88e84dad331a4d03e3a310adc2cd98c75d503/link-checker-0.1.1.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-z9fwk16q/link-checker/setup.py", line 31, in <module>
            long_description=read("README.md"),
          File "/tmp/pip-install-z9fwk16q/link-checker/setup.py", line 14, in read
            with codecs.open(path.join(here, *parts), 'r', encoding='utf-8') as filep:
          File "/usr/lib/python3.5/codecs.py", line 895, in open
            file = builtins.open(filename, mode, buffering)
        FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-z9fwk16q/link-checker/README.md'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-z9fwk16q/link-checker/

**Comment by budziq** [comment]
Hi @SilkAndSlug thanks for noticing!

I've uploaded 0.1.2 to pip. Please check if it works for you :)

**Comment by SilkAndSlug** [comment]
Yep, that worked.  :-)
